### ISSUE TITLE
Does not work on Firefox 74.0

### ISSUE THREAD

**Issue by simon04** [edg2s/w.wiki-bookmarklet#3]
![Peek 2020-03-25 23-22](https://user-images.githubusercontent.com/782446/77591115-9688ac80-6eef-11ea-93bb-13f2b4bcc192.gif)

After running the bookmarklet, a white page is opened and `true` is printed.

Firefox 74.0 on Arch Linux

**Comment by edg2s** [comment]
Thanks, the above patch should fix it!

**Comment by simon04** [comment]
Great, thank you! :sunflower:
